### ISSUE TITLE
Please correct the content of README.md regarding Client creation

### ISSUE THREAD

**Issue by hukuhuku-matsuo** [bleumink/streamlit-keycloak#11]
README.md needs to be updated.
Access-Type does not exist in the current keyclaok's Client configuration item. I am very confused.
I would be very happy if you could add an example of Client configuration.

Thanks for your great work!

**Comment by bleumink** [comment]
Ah yes, it's called Client Authentication now, in the capability config when you create a new client. This should be turned off, which is also the default. Adding a simple example is a good idea.

**Comment by hukuhuku-matsuo** [comment]
Thank you very much for your prompt response.
