### ISSUE TITLE
http://localhost:8080/realms/myrealm/protocol/openid-connect/3p-cookies/step1.html is 404

### ISSUE THREAD

**Issue by Winky678** [bleumink/streamlit-keycloak#30]
When I try the readme example code, there is an error in my localhost

http://localhost:8080/realms/myrealm/protocol/openid-connect/3p-cookies/step1.html is 404
![image](https://github.com/bleumink/streamlit-keycloak/assets/41333749/25856dfc-be05-4278-ac70-1a8292fed0f4)
 help please

**Comment by HerveMignot** [comment]
@Winky678 Did you find how to solve this? I have the same issue with a non local keycloak, but it may be due to the fact that it is an old version of keycloak. Thanks!
