### ISSUE TITLE
Unable to connect to Keycloak using the current configuration.

### ISSUE THREAD

**Issue by bqueguin** [bleumink/streamlit-keycloak#6]
Hi,

I just try to use your tool with a local instance of Keycloak 20.0.1
I created a new realm called **DEV** and a client called **my_client**.

Here is my code:

``` python
from streamlit_keycloak import login
import streamlit as st


def main():
    st.subheader(f"Welcome {keycloak.user_info['preferred_username']}!")
    st.write(f"Here is your OAuth2 token: {keycloak.access_token}")


st.title("Streamlit Keycloak example")
keycloak = login(
    url="http://localhost:8080",
    realm="DEV",
    client_id="my_client",
)

if keycloak.authenticated:
    main()
```

But I have the streamlit error message: **Unable to connect to Keycloak using the current configuration.**

Do you have any idea of what can be the problem?

Cheers
Bruno

**Comment by bleumink** [comment]
Hi Bruno,

Thanks for giving the tool a try. This error message appears when
keycloak-js fails to initialize in the frontend, e.g. when it can't connect
to the realm or client.

How have you set the client's access type? This should be set to public.


Kind regards,
Gideon

**Comment by bqueguin** [comment]
Hi Gideon,

Thanks for your response.

I just left the default configuration on Keycloak.
I can see that the client's access should be public:

![image](https://user-images.githubusercontent.com/23662595/202881378-14be31b1-c6ce-417d-a2f4-164110d782e8.png)

I am a noob with Keycloak so maybe I am not looking at the good parameter...

Bruno

**Comment by bqueguin** [comment]
An additional remark on my case:

When I add the following **init_options** parameter, I don't have the error but I don't have either the display of the connexion window, nothing happen actually.
 
``` python
keycloak = login(
    url="http://localhost:8080",
    realm="DEV",
    client_id="my_client",
    init_options={
        "checkLoginIframe": False
    }
)
```

**Comment by bleumink** [comment]
For a valid configuration, you should also set a redirect url and web
origin for the client.

When running locally the following should work:
 - redirect url: http://localhost/*
 - web origins: http://localhost:<port> or * to allow everything

It's recommended to set the web origin as specific as possible. For testing
the wildcard * would work fine, but it's not ideal in production.

**Comment by bqueguin** [comment]
You're right, it works now. 
Thank you so much!
<img width="583" alt="image" src="https://user-images.githubusercontent.com/23662595/202887541-244da826-6f4d-4c2d-983f-7c2464e86aca.png">
