### ISSUE TITLE
Group membership

### ISSUE THREAD

**Issue by bqueguin** [bleumink/streamlit-keycloak#7]
Hi Gadeon,

In the return dict **user_info**, I don't see any entry for the groups of the user. And after reading your README.md, I understood that it is implemented, am I right?

Have you got informations about groups with your configuration?

**Comment by bleumink** [comment]
Hi Bruno,

I had to look this up myself as well. The userinfo endpoint does not provide the group memberships by default, so will have to enable this yourself. To do this, open the client in the admin interface. Then go to 'client scopes' and open the dedicated scope and mappers for the client. Here you can configure a new mapper. Choose the 'groups membership' preset and configure it something like this:
![mapper](https://user-images.githubusercontent.com/19835894/202899354-bb94fef1-8bca-4a6c-9121-b0ffb5cce93f.PNG)

I'll probably include something along these lines in the documentation as well.

**Comment by bqueguin** [comment]
It works perfectly! Thanks!

Yes I think to add this in documentation could be usefull because it's not obvious how to add the group membership information into the output :)
